on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"  # every hour

permissions:
  contents: read
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: jippi
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "docker-pixelfed"
          image-tags: "pr-* branch-*"
          cut-off: 2w
          dry-run: true

      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: jippi
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "docker-pixelfed-php"
          image-tags: "pr-* branch-*"
          cut-off: 2w
          dry-run: true
