on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"  # every hour

permissions:
  contents: read
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: pcasteran/ghcr-cleaning-action@v1
        with:
          package: "docker-pixelfed"
          password: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true

      - uses: pcasteran/ghcr-cleaning-action@v1
        with:
          package: "docker-pixelfed-php"
          password: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
