name: Docker Cleanup

on:
  workflow_dispatch:

  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    # - cron: "30 8 * * *" # run at 8:30 AM UTC

jobs:
  clean_registry:
    name: Clean the container registry
    runs-on: ubuntu-latest
    steps:
      # See: https://github.com/dataaxiom/ghcr-cleanup-action?tab=readme-ov-file#action-options
      - name: Delete old PR + Branch images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GH_CLEANUP_PAT }}
          # dry-run: true
          delete-tags: "pr-*,branch-*"
          delete-untagged: false
          exclude-tags: "branch-main-*"
          older-than: 2 weeks

      # See: https://github.com/dataaxiom/ghcr-cleanup-action?tab=readme-ov-file#action-options
      - name: Delete old nightly images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GH_CLEANUP_PAT }}
          dry-run: true
          delete-tags: "nightly-*"
          delete-untagged: false
          older-than: 6 months

      # See: https://github.com/dataaxiom/ghcr-cleanup-action?tab=readme-ov-file#action-options
      - name: "Delete all untagged images"
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GH_CLEANUP_PAT }}
          dry-run: true
          delete-untagged: true
