---
name: pixelfed

on:
  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  # workflow_dispatch:

  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  # push:

  # See: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  # pull_request:

  workflow_run:
    workflows: ["PHP Base"]
    types: [completed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      # See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
      matrix:
        php_version:
          - 8.3
        target_runtime:
          - apache
          # - fpm
          # - nginx
        php_base:
          - apache
          # - fpm

        # See: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations
        # See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrixexclude
        exclude:
          # targeting [apache] runtime with [fpm] base type doesn't make sense
          - target_runtime: apache
            php_base: fpm

          # targeting [fpm] runtime with [apache] base type doesn't make sense
          - target_runtime: fpm
            php_base: apache

          # targeting [nginx] runtime with [apache] base type doesn't make sense
          - target_runtime: nginx
            php_base: apache

    # See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-and-the-default-behavior
    concurrency:
      group: pixelfed-${{ github.ref }}-${{ matrix.php_base }}-${{ matrix.php_version }}-${{ matrix.target_runtime }}
      cancel-in-progress: true

    permissions:
      contents: read
      packages: write

    steps:
      # checout this repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # checkout pixelfed source code
      - uses: actions/checkout@v4
        with:
          repository: "pixelfed/pixelfed"
          ref: "staging"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          version: v0.12.0 # *or* newer, needed for annotations to work

        # See: https://github.com/docker/login-action?tab=readme-ov-file#github-container-registry
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            name=ghcr.io/${{ github.repository }},enable=true
          flavor: |
            latest=auto
            suffix=-${{ matrix.target_runtime }}-${{ matrix.php_version }}
          tags: |
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=staging,enable=${{ github.ref == format('refs/heads/{0}', 'staging') }}
            type=pep440,pattern={{raw}}
            type=pep440,pattern=v{{major}}.{{minor}}
            type=ref,event=branch,prefix=branch-
            type=ref,event=pr,prefix=pr-
            type=ref,event=tag
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Docker meta (Cache)
        uses: docker/metadata-action@v5
        id: cache
        with:
          images: |
            name=ghcr.io/${{ github.repository }}-cache,enable=true
            name=${{ env.DOCKER_HUB_ORGANISATION }}/${{ env.DOCKER_HUB_REPO }}-cache,enable=${{ env.HAS_DOCKER_HUB_CONFIGURED }}
          flavor: |
            latest=auto
            suffix=-${{ matrix.target_runtime }}-${{ matrix.php_version }}
          tags: |
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}
            type=raw,value=staging,enable=${{ github.ref == format('refs/heads/{0}', 'staging') }}
            type=pep440,pattern={{raw}}
            type=pep440,pattern=v{{major}}.{{minor}}
            type=ref,event=branch,prefix=branch-
            type=ref,event=pr,prefix=pr-
            type=ref,event=tag
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: ${{ matrix.target_runtime }}-runtime
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
          sbom: true
          provenance: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            PHP_BASE_TYPE=${{ matrix.php_base }}
          cache-from: |
            type=gha,scope=${{ matrix.target_runtime }}-${{ matrix.php_base }}-${{ matrix.php_version }}
          cache-to: |
            type=gha,mode=max,scope=${{ matrix.target_runtime }}-${{ matrix.php_base }}-${{ matrix.php_version }}
            ${{ steps.cache.outputs.tags }}

      # goss validate the image
      #
      # See: https://github.com/goss-org/goss
      - uses: e1himself/goss-installation-action@v1
        with:
          version: "v0.4.4"
      - name: Execute Goss tests
        run: |
          dgoss run \
            -v "./.env.testing:/var/www/.env" \
            -e "EXPECTED_PHP_VERSION=${{ matrix.php_version }}" \
            -e "PHP_BASE_TYPE=${{ matrix.php_base }}" \
            ${{ steps.meta.outputs.tags }}
